#ifndef XGAME_CMAKE_H
#define XGAME_CMAKE_H
#pragma once

// The CMake project of a game: <project>/Cache/Script/CMakeLists.txt, made from the CMake files of its script modules (the ScriptModule compiler writes each one, see
// xscript_module_export.h: a list of the module's files, libraries and defines, and <module>_apply(target)). The project builds Game.dll, which links the game entry points of
// xscript_module.plugin and the import library of the engine's own ECS (LIONCore.lib: xECSV2 is compiled into LIONCore.dll, so the DLL shares the one component registry of the
// editor - it used to link the stale import library of a DLL the build no longer makes, and the game registered its components in a second registry that no world ever read).
//
// Pure text, no files touched, and nothing in it is the place of anything: the project is found from the file's own folder (<project>/Cache/Script) and the engine's two folders are
// given on the command line of the configure (-DXGPU_ROOT, -DXGPU_BIN_DIR), so the same game gives the same text on every machine and in every editor.
#include <cstdint>
#include <format>
#include <string>
#include <vector>

namespace xgame::cmake
{
    // One module of the game: its CMake file (from the project root, forward slashes) and a hash of that file's text.
    struct module_file
    {
        std::string     m_Guid;
        std::string     m_RelativePath;
        std::uint64_t   m_Hash = 0;
    };

    inline std::uint64_t Hash(std::string_view Text) noexcept            // FNV-1a: the same on every machine and every run
    {
        std::uint64_t H = 0xcbf29ce484222325ull;
        for (const unsigned char c : Text) { H ^= c; H *= 0x100000001b3ull; }
        return H;
    }

    // The text of CMakeLists.txt. The hash of each module's file is in it, so the text (and with it the file's time, the thing the configure and the build are compared with) changes
    // exactly when something the project is made of changes.
    inline std::string Assemble(const std::vector<module_file>& Modules) noexcept
    {
        std::string C;
        C += "# Generated by the Game compiler from the Game resource and the CMake files of its script modules - do not edit.\n";
        C += "# It is written again when the Game resource or the CMake file of one of its modules changes (the module lines name each file and a hash of its text).\n";
        C += "#   cmake -S <this folder> -B <build folder> -DXGPU_ROOT=<xLION checkout> -DXGPU_BIN_DIR=<the build folder of xLION that holds xLIONCore>\n";
        for (const auto& M : Modules) C += std::format("# module {} {:016x}\n", M.m_Guid, M.m_Hash);
        C += "\ncmake_minimum_required(VERSION 3.18)\nproject(Script LANGUAGES CXX)\n";
        C += "add_definitions(-DUNICODE -D_UNICODE)\nset(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n";
        C += "set(CMAKE_SUPPRESS_REGENERATION true)\nset(CMAKE_CONFIGURATION_TYPES \"Debug;Release\" CACHE STRING \"\" FORCE)\n\n";

        C += "get_filename_component(GAME_PROJECT_ROOT \"${CMAKE_CURRENT_LIST_DIR}/../..\" ABSOLUTE)\n";
        C += "if(NOT DEFINED XGPU_ROOT)\n  get_filename_component(XGPU_ROOT \"${GAME_PROJECT_ROOT}/..\" ABSOLUTE)       # the project sits next to the engine, like example.lionprj in the xLION checkout\nendif()\n";
        C += "if(NOT DEFINED XGPU_BIN_DIR)\n  message(FATAL_ERROR \"XGPU_BIN_DIR is not set: give the folder of xLION's build that holds xLIONCore (cmake -DXGPU_BIN_DIR=<xLION>/Build/xLION.vs2022)\")\nendif()\n\n";

        C += "# the CMake file of each script module: its files, libraries and defines, and <module>_apply(target)\n";
        C += "set(XSCRIPT_MODULE_PREFIXES)\n";
        for (const auto& M : Modules) C += std::format("include(\"${{GAME_PROJECT_ROOT}}/{}\")\n", M.m_RelativePath);
        C += "\nset(MODULE_PCH_HEADERS)\nset(XSCRIPT_RUNTIME_FILES)\n";
        C += "foreach(P IN LISTS XSCRIPT_MODULE_PREFIXES)\n";
        C += "  foreach(H IN LISTS ${P}_PCH_HEADERS)\n    list(APPEND MODULE_PCH_HEADERS \"$<$<COMPILE_LANGUAGE:CXX>:${H}>\")\n  endforeach()\n";
        C += "  list(APPEND XSCRIPT_RUNTIME_FILES ${${P}_RUNTIME_FILES})\n";
        C += "endforeach()\n\n";

        // Each consumer needs its own copy of xtextfile's and xproperty's backend (no shared state), which is why they are compiled into the DLL and, like the entry point,
        // kept out of the precompiled header.
        C += "set(BACKEND_SOURCES \"${XGPU_ROOT}/dependencies/xtextfile/source/xtextfile.cpp\" \"${XGPU_ROOT}/dependencies/xproperty/source/xcore/my_properties.cpp\")\n";
        C += "add_library(Game SHARED \"${XGPU_ROOT}/plugins/xscript_module.plugin/source/Runtime/xscript_game_entry.cpp\" ${BACKEND_SOURCES})\n";
        C += "target_include_directories(Game PRIVATE \"${XGPU_ROOT}\"";
        for (const char* pDep : { "xECSV2/src", "xerr", "xresource_guid", "xtextfile", "xproperty", "xresource_pipeline_v2", "xstrtool", "xcontainer", "xdelegate", "xscheduler", "xmath", "xbits", "box3d/include" })
            C += std::format(" \"${{XGPU_ROOT}}/dependencies/{}\"", pDep);
        C += ")\ntarget_compile_definitions(Game PRIVATE XECS_BUILD_SHARED)\n";
        C += "target_link_libraries(Game PRIVATE \"${XGPU_BIN_DIR}/xLIONCore/$<CONFIG>/LIONCore.lib\")\n";

        C += "\n# what each module brings: its sources, include folders, libraries and defines\n";
        C += "foreach(P IN LISTS XSCRIPT_MODULE_PREFIXES)\n  string(TOLOWER \"${P}\" p)\n  cmake_language(CALL ${p}_apply Game)\nendforeach()\n\n";
        C += "target_precompile_headers(Game PRIVATE \"$<$<COMPILE_LANGUAGE:CXX>:${XGPU_ROOT}/dependencies/xECSV2/src/xecs.h>\" ${MODULE_PCH_HEADERS})\n";
        C += "set_source_files_properties(${BACKEND_SOURCES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)\n\n";

        // The DLL goes to the compiled resources; the debugger finds symbols through the path embedded at link time, so the PDB is linked with only its bare name (/PDBALTPATH) and
        // the editor copies it next to the copy of the DLL it loads. That leaves the compiler's own PDB free to be rewritten while a debugger is attached. /FS lets concurrent
        // compiles share one PDB, which /MP makes likely.
        C += "set(GAME_DLL_DIR \"${GAME_PROJECT_ROOT}/Cache/Resources/Platforms/WINDOWS\")\n";
        C += "set_target_properties(Game PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG \"${GAME_DLL_DIR}/Debug\" RUNTIME_OUTPUT_DIRECTORY_RELEASE \"${GAME_DLL_DIR}\" PDB_OUTPUT_DIRECTORY \"${CMAKE_BINARY_DIR}/GamePdb\")\n";
        C += "set_property(TARGET Game APPEND_STRING PROPERTY LINK_FLAGS \" /PDBALTPATH:Game.pdb\")\n";
        C += "target_compile_options(Game PRIVATE /FS /MP /FC)\n\n";

        // The DLLs that the modules' libraries bring are copied next to the Game.dll that the editor loads (it reads this list): written when it changed only.
        C += "set(XSCRIPT_RUNTIME_MANIFEST \"\")\n";
        C += "foreach(F IN LISTS XSCRIPT_RUNTIME_FILES)\n  file(TO_NATIVE_PATH \"${F}\" N)\n  string(APPEND XSCRIPT_RUNTIME_MANIFEST \"${N}\\n\")\nendforeach()\n";
        C += "set(XSCRIPT_RUNTIME_MANIFEST_FILE \"${CMAKE_CURRENT_LIST_DIR}/runtime_files.txt\")\nset(XSCRIPT_RUNTIME_MANIFEST_OLD \"\")\n";
        C += "if(EXISTS \"${XSCRIPT_RUNTIME_MANIFEST_FILE}\")\n  file(READ \"${XSCRIPT_RUNTIME_MANIFEST_FILE}\" XSCRIPT_RUNTIME_MANIFEST_OLD)\nendif()\n";
        C += "if(NOT \"${XSCRIPT_RUNTIME_MANIFEST}\" STREQUAL \"${XSCRIPT_RUNTIME_MANIFEST_OLD}\")\n  file(WRITE \"${XSCRIPT_RUNTIME_MANIFEST_FILE}\" \"${XSCRIPT_RUNTIME_MANIFEST}\")\nendif()\n";
        return C;
    }
}

#endif // XGAME_CMAKE_H
